from menu import Menu
from product import Product
#menu1 = Menu()
#menu1.add_item("Burger", 8.99)
#menu1.add_item("Fries", 2.99)
#menu1.add_item("Soda", 1.49)
#enu1.display_menu()
#menu1.remove_item("Soda")
#menu1.display_menu()
#menu2 = Menu()
#enu2.add_item("Pizza", 12.99)
#menu2.add_item("Salad", 6.49)
#menu2.display_menu()
product1 = Product("Sausages",2.33)
product2 = Product("Soda",1.99)
product3 = Product("Burger",2.45)
product4 = Product("Cheese",1.89)
#print(product1.total_price())
#print(product2)
#print(product3)
menu1 = Menu()
menu1.add_product(product1)
menu1.add_product(product2)
menu1.add_product(product3)
menu1.add_product(product4)
menu1.display_menu()